version : '3'

services:
  mysql:
    image: mysql:latest
    container_name: node_mysql
    # volumes:
    #   - backend_app/db_sample:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: node_pa
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80

  node_backend:
    image: node:latest
    container_name: node_with_pa_msql
    build:
      context: backend_app/
    volumes: 
      - backend_app:/usr/src/app
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
    ports:
      - 5000:4006