version : '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: node_pa
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
  frontend:
    container_name: frontend_app
    build: ./frontend
    volumes: 
      - ./frontend/:/usr/src/frontend
      - /frontend/node_modules
    links:
      - node_backend
    depends_on:
      - node_backend
    environment:
      sharedHost: 192.168.0.101
    restart: on-failure
    ports:
      - 3000:3000
  node_backend:
    container_name: node_with_pa_msql
    build: ./backend_app
    environment:
      MYSQL_PORT: 3306
      PORT: 4006
      MYSQL_USER: root
      MYSQL_PW: root
      NODE_ENV: development
      MYSQL_HOST: mysql
      DATABASE_NAME: messenger_app_backend
      WAIT_HOSTS: mysql:3306
    volumes: 
      - ./backend_app/:/usr/src/app
      - /backend_app/node_modules
    links:
      - mysql
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - 4000:4006
  mysql:
    image: mysql:5.6
    container_name: node_mysql
    volumes:
      - ./backend_app/db_sample:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messenger_app_backend